---
- hosts:
  - all
  tasks: 
  
    - name: Enable EPEL Repository
      dnf:
        name: epel-release
        state: latest
    - name: Install Cobbler dependencies
      dnf:
        name:
          - createrepo_c 
          - httpd 
          - xorriso
          - mod_ssl 
          - python3-cheetah 
          - python3-netaddr 
          - python3-librepo 
          - python3-schema 
          - python3-yaml 
          - rsync 
          - syslinux 
          - tftp-server 
          - dnf-plugins-core 
          - dhcp-server
        state: latest

    - name: Enable CRB 
      command: /usr/bin/crb enable
      
    - name: Enable Cobbler Module
      command: dnf module enable cobbler:13 -y
      register: result
      changed_when:
        - '"Enabling module streams" in result.stdout'