---
- hosts:
  - all
  tasks: 
  
    - name: Enable EPEL Repository
      dnf:
        name: epel-release
        state: latest
    - name: Install Cobbler dependencies
      dnf:
        name:
          - createrepo_c 
          - httpd 
          - xorriso
          - mod_ssl 
          - python3-cheetah 
          - python3-netaddr 
          - python3-librepo 
          - python3-schema 
          - python3-yaml 
          - rsync 
          - syslinux 
          - tftp-server 
          - dnf-plugins-core 
          - dhcp-server
        state: latest

    - name: Enable Cobbler Module
      command: dnf module enable cobbler:3.3 -y
      register: result
      changed_when:
        - '"Enabling module streams" in result.stdout'
    
    - name: Install Cobbler
      dnf:
        name:
        - cobbler

    - name: Start Cobbler Services
      service:
        name: "{{ item }}" 
        state: started 
        enabled: yes 
      with_item: 
        - httpd 
        - dhcpd
        - tftp
        - cobblerd